CREATE TABLE [dbo].[AuditData] (
    [AUDIT_ID]     INT              IDENTITY (1, 1) NOT NULL,
    [USERID]       UNIQUEIDENTIFIER NOT NULL,
    [TABLE_NAME]   NVARCHAR (150)   NOT NULL,
    [TABLE_ID]     NVARCHAR (MAX)   NOT NULL,
    [SUMMARY]      NVARCHAR (MAX)   NOT NULL,
    [ACTION]       NVARCHAR (150)   NOT NULL,
    [CREATED_DATE] DATETIME         CONSTRAINT [DF_AuditData_CREATED_DATE] DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_AuditData] PRIMARY KEY CLUSTERED ([AUDIT_ID] ASC)
);

